name: poetry-testpypi
on:
  release:
    types: [prereleased]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry install --without dev,test,doc
      - name: Build and publish
        env:
          POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.TESTPYPI_TOKEN }}
        run: |
          poetry version $(git describe --tags)
          poetry build
          poetry publish --repository testpypi
